# Site settings
title: Lucia Coronel
email: coronlucia@gmail.com
description: > I'm a biophysicist
baseurl: "/Read-Only-Jekyll-Theme" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  crnlcu

# Build settings
markdown: kramdown
